/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "GNS3 Documentation",
  "tagline": "The official guide and reference for GNS3",
  "url": "https://mother.github.io",
  "baseUrl": "/",
  "favicon": "img/favicon.ico",
  "organizationName": "mother",
  "projectName": "gns3-docs",
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "http-equiv": "Content-Security-Policy",
        "content": "default-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.googletagmanager.com;"
      }
    }
  ],
  "themeConfig": {
    "algolia": {
      "apiKey": "878a16b0cf2e2172475efd1da20aa6fc",
      "appId": "GGI3KOZE2A",
      "indexName": "gns3",
      "algoliaOptions": {},
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "light",
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "alt": "GNS3 Docs",
        "src": "img/logocolour.png"
      },
      "items": [
        {
          "to": "docs/",
          "activeBasePath": "docs",
          "label": "Documentation",
          "position": "left"
        },
        {
          "href": "https://gns3.com/marketplace/appliances",
          "label": "Appliances",
          "position": "right"
        },
        {
          "href": "https://gns3.com",
          "label": "Community",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Documentation",
              "to": "docs/"
            }
          ]
        },
        {
          "title": "Visit Us",
          "items": [
            {
              "label": "GNS3 Community",
              "href": "https://gns3.com/community"
            },
            {
              "label": "GNS3 Academy",
              "href": "https://academy.gns3.com"
            },
            {
              "label": "GNS3 Certification",
              "href": "https://gns3.com/training"
            }
          ]
        },
        {
          "title": "Connect",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Galaxy Technologies LLC."
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "gtag": {
          "trackingID": "G-D2TYZDQ4ZW",
          "anonymizeIP": false
        },
        "docs": {
          "sidebarPath": "/Users/stevenyuen/Sites/gns3-docs/sidebars.js",
          "editUrl": "https://github.com/mother/gns3-docs/blob/master/"
        },
        "theme": {
          "customCss": "/Users/stevenyuen/Sites/gns3-docs/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
